### ISSUE TITLE
java.lang.IllegalStateException: No match found

### ISSUE THREAD

**Issue by kerbymart** [ArcBees/gae-studio#12]
When gae-studio-module-1.0-RC1 from WAR file is deployed and access it throws this error::

Uncaught exception from servlet
java.lang.IllegalStateException: No match found
    at java.util.regex.Matcher.group(Matcher.java:486)
    at com.arcbees.gaestudio.server.guice.RootServlet.extractLatestVersion(RootServlet.java:135)
    at com.arcbees.gaestudio.server.guice.RootServlet.retrieveLatestVersion(RootServlet.java:121)
    at com.arcbees.gaestudio.server.guice.RootServlet.buildAppConfig(RootServlet.java:84)
    at com.arcbees.gaestudio.server.guice.RootServlet.setParameters(RootServlet.java:78)
    at com.arcbees.gaestudio.server.guice.RootServlet.doGet(RootServlet.java:70)

Full stack trace can be found here: http://www.pastekit.com/xGlZxr

**Comment by kerbymart** [comment]
war files from here https://drive.google.com/a/arcbees.com/?tab=mo#folders/0B7Pd6DU1M9ZXalRpOENRdzhsaXM

**Comment by simonferronforget** [comment]
Happens always after admin login

**Comment by meriouma** [comment]
Have you tried the [latest version from maven](http://search.maven.org/#artifactdetails%7Ccom.arcbees.gaestudio%7Cgae-studio%7C1.0.1%7Cwar)?

**Comment by simonferronforget** [comment]
I just tried and it works like a charm. Thank you !
You should update the content of your Google Drive or update your documentation accordingly.
By the way, I was only able to find your Google Drive link through your Atlassian wiki, not your website.

**Comment by meriouma** [comment]
Thanks!
